server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  redis:
    cluster:
      nodes:
        - 192.168.3.130:7001
        - 192.168.3.130:7002
        - 192.168.3.130:7003
        - 192.168.3.130:7004
        - 192.168.3.130:7005
        - 192.168.3.130:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10   #连接池中的最大空闲连接
        min-idle: 5    #连接池中的最小空闲连接
  application:
    name: usian-cart-service


#购物车
CART_REDIS_KEY: CART_REDIS_KEY